---
title: "Spul models"
author: "Seoyeon Park B00768397"
date: "10/28/2021"
output: html_document
---

Syracosphaera pulchra

#Scientific name is only one factor level so gam returns an error - need to remove s(scientific_name, bs = "re")
`
```{r}
load("data_subsets.RData")
```

```{r}
library(mgcv)
```


##MODEL G

#Spul_modG

```{r}
Spul_modG <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + te(longitude, latitude, bs = c("cc","tp")) , data = data.Spul)
summary(Spul_modG)
```

##MODEL GS - environmental variables + group smoother scientific_name

#Spul_modGS_p

```{r}
Spul_modGS_p <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + s(p_an, scientific_name, bs = "fs") + te(longitude, latitude, bs = c("cc", "tp")), data = data.Spul, method = "REML")
summary(Spul_modGS_p)
```


#Spul_modGS_sistar

```{r}
Spul_modGS_sistar <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + s(si_star, scientific_name, bs = "fs") + te(longitude, latitude, bs = c("cc", "tp")), data = data.Spul, method = "REML")
summary(Spul_modGS_sistar)
```

#Spul_modGS_nistar

```{r}
Spul_modGS_nistar <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + s(ni_star, scientific_name, bs = "fs") + te(longitude, latitude, bs = c("cc", "tp")), data = data.Spul, method = "REML")
summary(Spul_modGS_nistar)
```

#Spul_modGS_s

```{r}
Spul_modGS_s <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + s(s_an, scientific_name, bs = "fs") + te(longitude, latitude, bs = c("cc", "tp")), data = data.Spul, method = "REML")
summary(Spul_modGS_s)
```

#Spul_modGS_t

```{r}
Spul_modGS_t <- gam(cells_per_litre ~ s(p_an, bs = "tp") + s(si_star, bs = "tp") + s(ni_star, bs = "tp") + s(s_an, bs = "tp") + s(t_an, bs = "tp") + s(t_an, scientific_name, bs = "fs") + te(longitude, latitude, bs = c("cc", "tp")), data = data.Spul, method = "REML")
summary(Spul_modGS_t)
```

